baseURL = 'https://eliasdaler.github.io'
languageCode = 'en-us'
title = "Elias Daler's blog"
theme = "etch"
markup.highlight.style='trac'
[author]
    name = "Elias Daler"
[params]
    copyright='© 2022 Elias Daler. All rights reserved.'
[outputFormats]
    [outputFormats.RSS]
        baseName = "feed"
